# Uncomment the next line to define a global platform for your project
 platform :ios, '14.4'

target 'iossdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iossdk
#pod 'Firebase/Messaging'
#pod 'Firebase/Core'
pod 'FirebaseCore'
pod 'FirebaseMessaging'
pod 'FirebaseAuth'
#pod 'SwiftyJSON'
#pod 'SwiftyJSON', :git =>'https://github.com/SwiftyJSON/SwiftyJSON.git'
# pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3' 
#pod 'JsonObject' 
  target 'iossdkTests' do
    # Pods for testing'

end
end
